
spring.application.name=Server
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.servlet.load-on-startup=1

logging.level.root=INFO
logging.level.Modelo.Dominio=DEBUG

## Conexion con la BD
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate

# --- Despliegue -------------------------------------------------------------->
server.port=5000
spring.datasource.url=jdbc:mysql://mysql-grupo8.clay4iokcy9z.us-east-1.rds.amazonaws.com:3306/grupo8_dds?serverTimezone=America/Buenos_Aires
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#server.ssl.key-store=classpath:utils/keystore.p12
#server.ssl.key-store-password=gonzalo
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=myalias
# Cookies seguras
#server.servlet.session.cookie.secure=true
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.same-site=Lax

# GitHub Login
spring.security.oauth2.client.registration.github.client-id=Ov23liQTVVtCyefBXCPF
spring.security.oauth2.client.registration.github.client-secret=0b87c1cc9ed5b24744f69a52f800bbaa372045bb

# Google Login
spring.security.oauth2.client.registration.google.client-id=336306645334-tffsi3j508e7g23inv490jvh5nsmjbi2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
