@startuml
class colaborador{
    -mediosDeContacto : [contacto]
    -donacionesHechas : [doncaion]
    -direccion
    +agregarDonacion(donacion) : void
}
class usuario{
    -username : string
    -clave : string
    -colaborador : colaborador
}
class personaHumana extends colaborador{
    -nombre : string
    -apellido : string
    -fechaDeNacimiento : string
    -capacidadDeColaboracion : string
    -donaciones : [donacion]
    +donarDinero(donacionDeDinero) : void
    +donarVianda(vianda) : void
    +distribuir(distribucion) : void
}
class distribucion{
    -personaDistribuidora : personaHumana
    -origen : heladera
    -destino : heladera
    -viandasAMover : int
    -motivoDeDistribucion : motivo
    -fecha : fecha
}
enum motivo{
    fantan viandas en el destino
    heladera rota
}
enum tipoDeDonacion{
    DINERO
    VIANDA
}
class donacion{
}
class gestorDeContribucion{
    -colaborador : colaborador
    -contribucion : contriubcion
}
class donacionDeDinero extends donacion{
    -donante : persona
    -fecha : string
    -monto : float
    -fracuencia : string
}
class contacto{
    -colaborador : colaborador
    -tipoDeContacto : medio
    }
interface medio{
    +contactar() : void
}
class personaJuridica extends colaborador{
    -razonSocial : string
    -tipoDePersonaJuridica : tipoDPJ
    +donarDinero(donacionDeDinero) : void
    +hacerseCardoDe(heladera) : void
}
enum tipoDPJ{
    institucion
    ONG
    gubernamental
    empresa
}
class vianda{
    -comida : comida
    -vencimiento : string
    -heladera : heladera
    -calorias : int
    -peso : float
    -entregada : bool
}
class donacionDeVianda extends donacion{
    -vianda : vianda
    -fechaDeDonacion : string
}
enum comida{
}
class heladera{
    -ID : string
    -ubicacion : ubicacion
    -capacidadEnViandas : int
    -fechaDeArranque : string
    -darDeBaja() : void
}
class ubicacion{
    -nombre : string
    -longitud : string
    -latitud : string
    -direccion : string
    +contribuir(vianda) : void
    +registrarComoVulnerable() : void
    +darDeAlta() : void
}
class vulnerables{
    -nombre : string
    -fechaDeRegistro : string
    -enSituacionDeCalle : bool
    -domiciolio : string
    -DNI : string
    -menoresAcargo : int
}
interface donacionesHumanas{
  +donar()
}
enum donacionesJuridicas{
    dinero
    hacerseCargo
}
class contribucionHumana{
    tipoDeDonacion : donacionesHumanas
    colaborador : colaborador
}

contacto *-- medio
medio <|-- whatsapp
medio <|-- mail  
medio <|-- telefono  
vianda -- donacionDeVianda
usuario -- colaborador
colaborador -- contacto
tipoDPJ -- personaJuridica


contribucionJuridica -- donacionesJuridicas

contribucionHumana *-- donacionesHumanas
dinero --|> donacionesHumanas
viandas --|> donacionesHumanas 


@enduml